IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'infra')
BEGIN
    EXEC('CREATE SCHEMA [infra]');
END
GO

IF OBJECT_ID(N'infra.Idempotency', N'U') IS NULL
BEGIN
    CREATE TABLE infra.Idempotency (
        IdempotencyKey NVARCHAR(200) NOT NULL PRIMARY KEY,
        Status TINYINT NOT NULL,
        LockedUntil DATETIMEOFFSET(3) NULL,
        LockedBy UNIQUEIDENTIFIER NULL,
        FailureCount INT NOT NULL DEFAULT 0,
        CreatedAt DATETIMEOFFSET(3) NOT NULL DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIMEOFFSET(3) NOT NULL DEFAULT SYSUTCDATETIME(),
        CompletedAt DATETIMEOFFSET(3) NULL
    );
END
GO
