CREATE SCHEMA IF NOT EXISTS "$SchemaName$";

CREATE TABLE IF NOT EXISTS "$SchemaName$"."MetricDef" (
    "MetricDefId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(128) NOT NULL UNIQUE,
    "Unit" varchar(32) NOT NULL,
    "AggKind" varchar(16) NOT NULL,
    "Description" varchar(512) NOT NULL
);

ALTER TABLE "$SchemaName$"."MetricDef"
    ADD COLUMN IF NOT EXISTS "MetricDefId" integer GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS "Name" varchar(128) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "Unit" varchar(32) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "AggKind" varchar(16) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "Description" varchar(512) NOT NULL DEFAULT '';

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_MetricDef_Name"
    ON "$SchemaName$"."MetricDef" ("Name");

CREATE TABLE IF NOT EXISTS "$SchemaName$"."MetricSeries" (
    "SeriesId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MetricDefId" integer NOT NULL REFERENCES "$SchemaName$"."MetricDef" ("MetricDefId"),
    "Service" varchar(64) NOT NULL,
    "InstanceId" uuid NOT NULL,
    "TagsJson" varchar(1024) NOT NULL DEFAULT '{}',
    "TagHash" bytea NOT NULL,
    "CreatedUtc" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UQ_MetricSeries" UNIQUE ("MetricDefId", "Service", "InstanceId", "TagHash")
);

ALTER TABLE "$SchemaName$"."MetricSeries"
    ADD COLUMN IF NOT EXISTS "SeriesId" bigint GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS "MetricDefId" integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "Service" varchar(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "InstanceId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    ADD COLUMN IF NOT EXISTS "TagsJson" varchar(1024) NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS "TagHash" bytea NOT NULL DEFAULT E'\\x'::bytea,
    ADD COLUMN IF NOT EXISTS "CreatedUtc" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_MetricSeries_Def_Service_Instance_TagHash"
    ON "$SchemaName$"."MetricSeries" ("MetricDefId", "Service", "InstanceId", "TagHash");

CREATE TABLE IF NOT EXISTS "$SchemaName$"."MetricPointMinute" (
    "SeriesId" bigint NOT NULL REFERENCES "$SchemaName$"."MetricSeries" ("SeriesId"),
    "BucketStartUtc" timestamptz NOT NULL,
    "BucketSecs" smallint NOT NULL,
    "ValueSum" double precision NULL,
    "ValueCount" integer NULL,
    "ValueMin" double precision NULL,
    "ValueMax" double precision NULL,
    "ValueLast" double precision NULL,
    "P50" double precision NULL,
    "P95" double precision NULL,
    "P99" double precision NULL,
    "InsertedUtc" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_MetricPointMinute" PRIMARY KEY ("SeriesId", "BucketStartUtc", "BucketSecs")
);

ALTER TABLE "$SchemaName$"."MetricPointMinute"
    ADD COLUMN IF NOT EXISTS "SeriesId" bigint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "BucketStartUtc" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS "BucketSecs" smallint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "ValueSum" double precision NULL,
    ADD COLUMN IF NOT EXISTS "ValueCount" integer NULL,
    ADD COLUMN IF NOT EXISTS "ValueMin" double precision NULL,
    ADD COLUMN IF NOT EXISTS "ValueMax" double precision NULL,
    ADD COLUMN IF NOT EXISTS "ValueLast" double precision NULL,
    ADD COLUMN IF NOT EXISTS "P50" double precision NULL,
    ADD COLUMN IF NOT EXISTS "P95" double precision NULL,
    ADD COLUMN IF NOT EXISTS "P99" double precision NULL,
    ADD COLUMN IF NOT EXISTS "InsertedUtc" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_MetricPointMinute_Key"
    ON "$SchemaName$"."MetricPointMinute" ("SeriesId", "BucketStartUtc", "BucketSecs");

CREATE INDEX IF NOT EXISTS "IX_MetricPointMinute_ByTime"
    ON "$SchemaName$"."MetricPointMinute" ("BucketStartUtc");
